version: '3.8'

services:
  lucia-server:
    image: ubuntu:22.04
    container_name: lucia-server
    #도커 자동시작 옵션
    #restart: unless-stopped
    # GPU 할당
    runtime: nvidia
    gpus: all

    # -it
    stdin_open: true
    tty: true

    # 공유 메모리 크기
    shm_size: 64g

    # IPC namespace 공유
    ipc: host

    # ulimit 설정
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864

    # 포트 매핑
    ports:
      - "3306:3306"
      - "3545:3545"

    # 볼륨 마운트 (호스트 경로:컨테이너 경로)
    volumes:
      - '/home/lucia/ProjectLucia/docker:/workspace'

    # CUDA 환경 변수 — 컨테이너가 시작될 때 자동으로 적용
    environment:
      CUDA_HOME: /usr/local/cuda
      PATH: /usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/lib:/usr/lib

    # (선택) 컨테이너 내 작업 디렉토리
    working_dir: /workspace

    #mysql 자동시작 옵션
    #command: bash -c "service mysql start && bash"
